name = "backend"
compatibility_date = "2024-08-06"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzRmYzkxNzUtNzdkNy00YjAzLTgyMTgtYWJiY2NjODk4YTY2IiwidGVuYW50X2lkIjoiYTc3ZmYyNzkyNTA1NjQ2ZTU3ZmYzYzA2OGE4MGFmMjBhYjQzYzFjYWQzYTYwN2Q3NjcxNDYzZTlkYTQyNmNiMiIsImludGVybmFsX3NlY3JldCI6IjI4ZTQzMmMzLWExMmUtNDg3NS04MWNlLTFlMjdlYWQ1NjBkZSJ9._HaIlR-vxPu9hi4e_9_1UnDBbTD39OH6ACk4BG4gCMQ"
JWT_SECRET = "jwtsecret"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"